### ISSUE TITLE
High pitch noise in video

### ISSUE THREAD

**Issue by carlosjoserg** [CanyoneroRobotics/TFM#22]
In the video @simium made and @marcgenevat sent me, I hear a high pitch noise when actuating the motors, that is typically caused by a low and audible PWM frequency.

I see you are using the default frequency of 1.6Khz [here](https://github.com/CanyoneroRobotics/TFM/blob/roscontrol/arduino_sketchbook/arduino_canyonero/arduino_canyonero.ino#L244). 

If the H-bridge you have supports a non-audible frequency (>20Khz), then it'd be pleasantly quiet if you set a higher PWM frequency.

If I was mistaken about the noise, then forget this issue.

**Comment by simium** [comment]
In this project we are using the Motor Shield v2 by Adafruit, which uses the PCA9865 PWM chip to generate the desired PWM signals for the motors. The problem is that this IC provides a maximum frequency of 1.6Khz (it's actually designed to drive LEDs, not motors, but it keeps costs down)

In a future version of Canyonero we could get better motor drivers that have more pleasant frequencies, but there's not much we can do about this right now with current hardware.

**Comment by carlosjoserg** [comment]
:+1:
